fix item_appeared
OpenKore/openkore pull request #3353
Opened 2021-02-18 19:44 UTC by ya4ept

nameID changed from 2 bytes to 4 bytes

should fix this: https://github.com/OpenKore/openkore/commit/10b225b64508ab0a7771fa4b37bc048d6ba703ab#commitcomment-47254947

2021-02-18 20:16 UTC, alisonrag requested changes

2021-02-18 20:16 UTC, alisonrag commented on src/Network/Receive/Zero.pm
> +# I think this is extra code in the received packages
this is used in xkore 3 and 2, if not set, openkore will use old character pages and other old packets, and cRo has support for both cause use nprotect gameguard

2021-02-19 04:36 UTC, alisonrag approved these changes

2021-02-19 04:36 UTC, alisonrag commented
just wait the @hubertyang88 test

2021-02-19 06:52 UTC, alisonrag requested changes
sorry i just saw the file name now, cRO is at cRO.pm, this server is not equals to Zero.pm
so the changes should be done at Receive/cRO.pm

2021-02-19 10:56 UTC, hubertyang88 commented
================================================
<< Received packet:      0ADD - Item Exists [24 bytes]   Feb 19 18:47:02 2021
  0>  DD 0A 8A 85 00 00 FC 01    00 00 00 00 01 9F 00 BB    ................
 16>  00 06 0C 02 00 00 00 00                               ........
Item appeared : name (0) x 2 (159, 187)

I add '0ADD' to cRo.pm , it works !
I ignored other "packets changes" in zRo.pm , because my op works fine , should I change the file like  zRo.pm?
[cRO.txt](https://github.com/OpenKore/openkore/files/6009425/cRO.txt)
this is my cro.pm

2021-02-19 13:52 UTC, ya4ept commented
moved the changes to cro.pm
@hubertyang88 please test again

PS; did the hard discard all changes at zero.pm

2021-02-19 13:54 UTC, alisonrag approved these changes

2021-02-19 15:21 UTC, hubertyang88 commented
I replace cro.pm with new one , it looks good , no problem found , Thanks!

2021-02-19 15:26 UTC, merged