fix party share at private servers
OpenKore/openkore pull request #3574
Opened 2022-04-07 21:12 UTC by alisonrag

2022-04-07 21:20 UTC, ya4ept requested changes

2022-04-07 21:20 UTC, ya4ept commented on src/Network/Send/kRO/Sakexe_0.pm
>  sub sendPartyOption {
let's move this function to send.pm ?

2022-04-07 22:36 UTC, ya4ept approved these changes

2022-04-08 00:25 UTC, ya4ept commented
lets merge

2022-04-08 02:15 UTC, sctnightcore approved these changes

2022-04-08 03:17 UTC, merged